include:
  - project: viz/ci/gitlabpipelines
    file: index.yml

docker:
  extends: .build-image-using-kaniko
  tags:
    - kubernetes
  variables:
    KUBERNETES_MEMORY_LIMIT: 3Gi
    KUBERNETES_MEMORY_REQUEST: 3Gi

publish-spectacle:
  extends: .publish-image-using-kaniko
  variables:
    REGISTRY_IMAGE_TAG: latest
  tags:
    - kubernetes
    variables:
      KUBERNETES_MEMORY_LIMIT: 3Gi
      KUBERNETES_MEMORY_REQUEST: 3Gi
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
