export interface ApplicationConfig {
  VEEDRIVE_WS_PATH: string
  FILE_BROWSER_WIDTH: number
  FILE_BROWSER_HEIGHT: number
  VIEWPORT_WIDTH: number
  VIEWPORT_HEIGHT: number
  MINIMUM_FRAME_LONG_SIDE: number
  MAXIMUM_FRAME_LONG_SIDE: number
  ALLOW_SCALE_WITH_MOUSEWHEEL: boolean
  ALLOW_MAX_LAUNCHER_MENUS: number
}
